# Generated by Django 5.2.4 on 2025-07-23 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butterflies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='butterflycollection',
            name='butterflyID',
            field=models.OneToOneField(blank=True, help_text='Unique ID linking this butterfly collection to a specific trap.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='butterfly_collection', to='butterflies.trap'),
        ),
        migrations.AddField(
            model_name='trap',
            name='butterflyID',
            field=models.CharField(blank=True, help_text='Unique butterfly ID for linking this trap to a butterfly collection.', max_length=100, null=True, unique=True),
        ),
    ]
