# Generated by Django 5.2.4 on 2025-09-07 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butterflies', '0002_fix_locality_fk_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='exact_loc',
            field=models.BooleanField(blank=True, help_text='Boolean field (True/False).', null=True),
        ),
    ]
