# Generated by Django 5.2.4 on 2025-07-23 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butterflies', '0003_alter_butterflycollection_butterflyid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='butterflycollection',
            name='butterflyID',
        ),
        migrations.AddField(
            model_name='butterflycollection',
            name='trap',
            field=models.ForeignKey(blank=True, help_text='Trap to which this butterfly collection is linked. Dropdown shows butterflyID and name.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='butterfly_collections', to='butterflies.trap'),
        ),
        migrations.AlterField(
            model_name='trap',
            name='butterflyID',
            field=models.CharField(blank=True, help_text='Unique butterfly ID for this trap.', max_length=100, null=True, unique=True),
        ),
    ]
