# Generated by Django 5.2.4 on 2025-09-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butterflies', '0003_alter_specimen_exact_loc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='exact_loc',
            field=models.CharField(blank=True, choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], help_text='Dropdown: "TRUE", "FALSE".', max_length=5, null=True),
        ),
    ]
