# Generated by Django 5.2.4 on 2025-07-25 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butterflies', '0003_remove_locality_description_remove_locality_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initials',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='initials',
            name='notes',
        ),
        migrations.AddField(
            model_name='initials',
            name='name',
            field=models.CharField(blank=True, default=None, help_text='Full name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='initials',
            name='relationshipOrTitle',
            field=models.CharField(blank=True, default=None, help_text='Relationship or title', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='initials',
            name='yearAndTerm',
            field=models.CharField(blank=True, default=None, help_text='Year and term', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='initials',
            name='initials',
            field=models.CharField(blank=True, default=None, help_text='Initials (superkey)', max_length=10, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='initials',
            table='initialsTable',
        ),
    ]
