# Generated by Django 5.2.4 on 2025-07-25 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butterflies', '0004_remove_initials_full_name_remove_initials_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specimen',
            name='catalog_number',
        ),
        migrations.RemoveField(
            model_name='specimen',
            name='date_collected',
        ),
        migrations.RemoveField(
            model_name='specimen',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='specimen',
            name='specimen_number',
        ),
        migrations.RemoveField(
            model_name='specimen',
            name='termNumbetableOfOrigin',
        ),
        migrations.AddField(
            model_name='specimen',
            name='catalogNumber',
            field=models.CharField(blank=True, default=None, help_text='Unique voucher code.', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='coordinateUncertaintyInMeters',
            field=models.CharField(blank=True, help_text='Text.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='dateIdentified',
            field=models.DateField(blank=True, help_text='Date (DD-MMM-YYYY; ex., 27-Nov-2024).', null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='day',
            field=models.CharField(blank=True, help_text='Dropdown/typeable.', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='decimalLatitude',
            field=models.CharField(blank=True, help_text='Text/number (XX.XXXXXX).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='decimalLongitude',
            field=models.CharField(blank=True, help_text='Text/number (XX.XXXXXX).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='eventDate',
            field=models.DateField(blank=True, help_text='Date (DD-MMM-YYYY; ex., 27-Nov-2024).', null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='eventTime',
            field=models.TimeField(blank=True, help_text='Time (XX:XX) military format.', null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='exact_loc',
            field=models.CharField(blank=True, choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], help_text='Dropdown: "TRUE", "FALSE".', max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='family',
            field=models.CharField(blank=True, help_text='Text/write in.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='genus',
            field=models.CharField(blank=True, help_text='Text/write in.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='georeferenceProtocol',
            field=models.TextField(blank=True, help_text='Text.', null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='georeferencedBy',
            field=models.ForeignKey(help_text='Dropdown: initials from Initials table.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='georeferenced_specimens', to='butterflies.initials'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='georeferencedDate',
            field=models.DateField(blank=True, help_text='Date (DD-MMM-YYYY; ex., 27-Nov-2024).', null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='habitat',
            field=models.CharField(blank=True, help_text='Text.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='habitatNotes',
            field=models.TextField(blank=True, help_text='Text.', null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='identificationReferences',
            field=models.TextField(blank=True, help_text='Text.', null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='identificationRemarks',
            field=models.TextField(blank=True, help_text='Text.', null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='identifiedBy',
            field=models.ForeignKey(help_text='Dropdown: initials from Initials table.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identified_specimens', to='butterflies.initials'),
        ),
        migrations.AddField(
            model_name='specimen',
            name='infraspecificEpithet',
            field=models.CharField(blank=True, help_text='Text/write in.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='localityDescriptionNotes',
            field=models.TextField(blank=True, help_text='Text.', null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='maximumElevationInMeters',
            field=models.CharField(blank=True, help_text='Text/number (X,XXX).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='minimumElevationInMeters',
            field=models.CharField(blank=True, help_text='Text/number (X,XXX).', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='modified',
            field=models.TextField(blank=True, help_text="Append-only: Each entry is 'MM-DD-YYYY, initials, description'; entries separated by semicolon. Use form to add, not edit.", null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='month',
            field=models.CharField(blank=True, help_text='Dropdown/typeable.', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='occurrenceRemarks',
            field=models.TextField(blank=True, help_text='Text.', null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='samplingProtocol',
            field=models.TextField(blank=True, help_text='Text.', null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='specificEpithet',
            field=models.CharField(blank=True, help_text='Text/write in.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='specimenNumber',
            field=models.CharField(blank=True, default=None, help_text='Manual entry. If duplicate, error.', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='subfamily',
            field=models.CharField(blank=True, help_text='Text/write in.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='subtribe',
            field=models.CharField(blank=True, help_text='Text/write in.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='tribe',
            field=models.CharField(blank=True, help_text='Text/write in.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='specimen',
            name='year',
            field=models.CharField(blank=True, help_text='Dropdown/typeable: 1900-2050.', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='behavior',
            field=models.TextField(blank=True, help_text='Text.', null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='disposition',
            field=models.TextField(blank=True, help_text="Append-only: Each entry is 'MM-DD-YYYY, initials, description'; entries separated by semicolon. Use form to add, not edit.", null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='locality',
            field=models.ForeignKey(help_text='Dropdown: localityCode from Locality table.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='butterflies.locality'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='recordedBy',
            field=models.ForeignKey(help_text='Dropdown: initials from Initials table.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='butterflies.initials'),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('.', '.')], help_text='Dropdown: male/female/.', max_length=6),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='uploaded_iNaturalist',
            field=models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], help_text='Dropdown: TRUE/FALSE.', max_length=5),
        ),
        migrations.AlterModelTable(
            name='specimen',
            table='specimenTable',
        ),
    ]
