# Generated by Django 5.2.4 on 2025-09-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butterflies', '0005_date_fields_to_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='specimenNumber',
            field=models.CharField(blank=True, default=None, help_text='Manual entry. Can have duplicates across different locations.', max_length=100, null=True),
        ),
    ]
