# Generated by Django 5.2.7 on 2025-11-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butterflies', '0007_add_performance_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='month',
            field=models.CharField(blank=True, help_text='Dropdown/typeable.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='specimenNumber',
            field=models.CharField(blank=True, default=None, help_text='Manual entry. Can have duplicates across different locations.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='year',
            field=models.CharField(blank=True, help_text='Dropdown/typeable: 1900-2050.', max_length=4, null=True),
        ),
    ]
