# Generated by Django 5.2.4 on 2025-08-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butterflies', '0007_remove_specimen_habitat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locality',
            options={'verbose_name_plural': 'Localities'},
        ),
    ]
