# Generated by Django 5.2.7 on 2025-11-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butterflies', '0009_add_sorting_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='specimen',
            name='specimen_event_idx',
        ),
        migrations.RemoveIndex(
            model_name='specimen',
            name='specimen_catalog_idx',
        ),
        migrations.AlterField(
            model_name='specimen',
            name='eventDate',
            field=models.DateField(blank=True, help_text='Date of the event or collection.', null=True),
        ),
    ]
