# Generated by Django 6.0 on 2026-04-28 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butterflies', '0010_remove_specimen_specimen_event_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specimen',
            options={},
        ),
    ]
