# Generated by Django 6.0 on 2026-04-28 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butterflies', '0011_alter_specimen_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='specimen',
            index=models.Index(fields=['-eventDate', '-eventTime', '-year', '-catalogNumber'], name='specimenTab_eventDa_6b88ce_idx'),
        ),
    ]
