# Generated by Django 5.2.4 on 2025-08-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butterflies', '0014_alter_specimen_dateidentified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='dateIdentified',
            field=models.CharField(blank=True, help_text='Date (DD-MMM-YYYY; ex., 27-Nov-2024).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='eventDate',
            field=models.CharField(blank=True, help_text='Date (DD-MMM-YYYY; ex., 27-Nov-2024).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='eventTime',
            field=models.CharField(blank=True, help_text='Time (XX:XX) military format.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='georeferencedDate',
            field=models.CharField(blank=True, help_text='Date (DD-MMM-YYYY; ex., 27-Nov-2024).', max_length=100, null=True),
        ),
    ]
