# Generated by Django 5.2.4 on 2025-08-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butterflies', '0015_alter_specimen_dateidentified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='month',
            field=models.CharField(blank=True, help_text='Dropdown/typeable.', max_length=10, null=True),
        ),
    ]
