# Generated by Django 5.2.4 on 2025-07-25 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butterflies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initials', models.CharField(max_length=10, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termNumbetableOfOrigin', models.CharField(help_text='Mapping of terms to tables; unique or linking field.', max_length=100)),
                ('specimen_number', models.CharField(help_text='Specimen number.', max_length=100)),
                ('catalog_number', models.CharField(help_text='Catalog number.', max_length=100)),
                ('uploaded_iNaturalist', models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], help_text='Indicates if uploaded to iNaturalist. Dropdown: TRUE/FALSE.', max_length=5)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('.', '.')], help_text='Sex of specimen. Dropdown: male/female/.', max_length=6)),
                ('behavior', models.TextField(blank=True, help_text='Behavioral observations.', null=True)),
                ('disposition', models.TextField(blank=True, help_text='List of disposition events.', null=True)),
                ('date_collected', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('locality', models.ForeignKey(help_text='Locality of collection.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='butterflies.locality')),
                ('recordedBy', models.ForeignKey(help_text='Collector initials.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='butterflies.initials')),
            ],
        ),
        migrations.DeleteModel(
            name='ButterflyCollection',
        ),
        migrations.DeleteModel(
            name='Trap',
        ),
    ]
