# Generated by Django 5.2.4 on 2025-07-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butterflies', '0002_initials_locality_specimen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locality',
            name='description',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='locality',
            name='name',
        ),
        migrations.AddField(
            model_name='locality',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='district',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='habitat',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='localityCode',
            field=models.CharField(blank=True, default=None, help_text='Unique code for locality (superkey)', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='province',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='siteDescription',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='locality',
            name='siteName',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='locality',
            table='localityTable',
        ),
    ]
