# Generated by Django 5.2.4 on 2025-07-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butterflies', '0005_remove_specimen_catalog_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='catalogNumber',
            field=models.CharField(blank=True, default=None, help_text='Auto-generated: year-localityCode-specimenNumber (nnnn). Do not edit.', max_length=100, null=True, unique=True),
        ),
    ]
