# Generated by Django 5.2.4 on 2025-07-31 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butterflies', '0006_alter_specimen_catalognumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specimen',
            name='habitat',
        ),
    ]
