# Generated by Django 5.2.4 on 2025-08-04 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butterflies', '0008_alter_locality_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='behavior',
            field=models.TextField(blank=True, help_text="Append-only: Each entry is 'MM-DD-YYYY, initials, description'; entries separated by semicolon. Use form to add, not edit.", null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='georeferenceProtocol',
            field=models.TextField(blank=True, help_text="Append-only: Each entry is 'MM-DD-YYYY, initials, description'; entries separated by semicolon. Use form to add, not edit.", null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='habitatNotes',
            field=models.TextField(blank=True, help_text="Append-only: Each entry is 'MM-DD-YYYY, initials, description'; entries separated by semicolon. Use form to add, not edit.", null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='identificationReferences',
            field=models.TextField(blank=True, help_text="Append-only: Each entry is 'MM-DD-YYYY, initials, description'; entries separated by semicolon. Use form to add, not edit.", null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='identificationRemarks',
            field=models.TextField(blank=True, help_text="Append-only: Each entry is 'MM-DD-YYYY, initials, description'; entries separated by semicolon. Use form to add, not edit.", null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='localityDescriptionNotes',
            field=models.TextField(blank=True, help_text="Append-only: Each entry is 'MM-DD-YYYY, initials, description'; entries separated by semicolon. Use form to add, not edit.", null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='occurrenceRemarks',
            field=models.TextField(blank=True, help_text="Append-only: Each entry is 'MM-DD-YYYY, initials, description'; entries separated by semicolon. Use form to add, not edit.", null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='samplingProtocol',
            field=models.TextField(blank=True, help_text="Append-only: Each entry is 'MM-DD-YYYY, initials, description'; entries separated by semicolon. Use form to add, not edit.", null=True),
        ),
    ]
