# Generated by Django 5.2.4 on 2025-08-08 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butterflies', '0010_alter_initials_initials_alter_initials_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initials',
            name='initials',
            field=models.CharField(blank=True, default=None, help_text='Initials (superkey)', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='initials',
            name='name',
            field=models.CharField(blank=True, default=None, help_text='Full name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='initials',
            name='relationshipOrTitle',
            field=models.CharField(blank=True, default=None, help_text='Relationship or title', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='initials',
            name='yearAndTerm',
            field=models.CharField(blank=True, default=None, help_text='Year and term', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='locality',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='locality',
            name='district',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='locality',
            name='habitat',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locality',
            name='localityCode',
            field=models.CharField(blank=True, default=None, help_text='Unique code for locality (superkey)', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='locality',
            name='province',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='locality',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='locality',
            name='siteDescription',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='locality',
            name='siteName',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='behavior',
            field=models.TextField(blank=True, help_text="Append-only: Each entry is 'MM-DD-YYYY, initials, description'; entries separated by semicolon. Use form to add, not edit.", null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='catalogNumber',
            field=models.CharField(blank=True, default=None, help_text='Auto-generated: year-localityCode-specimenNumber (nnnn). Do not edit.', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='coordinateUncertaintyInMeters',
            field=models.CharField(blank=True, help_text='Text.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='day',
            field=models.CharField(blank=True, help_text='Dropdown/typeable.', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='decimalLatitude',
            field=models.CharField(blank=True, help_text='Text/number (XX.XXXXXX).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='decimalLongitude',
            field=models.CharField(blank=True, help_text='Text/number (XX.XXXXXX).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='disposition',
            field=models.TextField(blank=True, help_text="Append-only: Each entry is 'MM-DD-YYYY, initials, description'; entries separated by semicolon. Use form to add, not edit.", null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='exact_loc',
            field=models.CharField(blank=True, choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], help_text='Dropdown: "TRUE", "FALSE".', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='family',
            field=models.CharField(blank=True, help_text='Text/write in.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='genus',
            field=models.CharField(blank=True, help_text='Text/write in.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='georeferenceProtocol',
            field=models.TextField(blank=True, help_text="Append-only: Each entry is 'MM-DD-YYYY, initials, description'; entries separated by semicolon. Use form to add, not edit.", null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='habitatNotes',
            field=models.TextField(blank=True, help_text="Append-only: Each entry is 'MM-DD-YYYY, initials, description'; entries separated by semicolon. Use form to add, not edit.", null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='identificationReferences',
            field=models.TextField(blank=True, help_text="Append-only: Each entry is 'MM-DD-YYYY, initials, description'; entries separated by semicolon. Use form to add, not edit.", null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='identificationRemarks',
            field=models.TextField(blank=True, help_text="Append-only: Each entry is 'MM-DD-YYYY, initials, description'; entries separated by semicolon. Use form to add, not edit.", null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='infraspecificEpithet',
            field=models.CharField(blank=True, help_text='Text/write in.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='localityDescriptionNotes',
            field=models.TextField(blank=True, help_text="Append-only: Each entry is 'MM-DD-YYYY, initials, description'; entries separated by semicolon. Use form to add, not edit.", null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='maximumElevationInMeters',
            field=models.CharField(blank=True, help_text='Text/number (X,XXX).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='minimumElevationInMeters',
            field=models.CharField(blank=True, help_text='Text/number (X,XXX).', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='modified',
            field=models.TextField(blank=True, help_text="Append-only: Each entry is 'MM-DD-YYYY, initials, description'; entries separated by semicolon. Use form to add, not edit.", null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='month',
            field=models.CharField(blank=True, help_text='Dropdown/typeable.', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='occurrenceRemarks',
            field=models.TextField(blank=True, help_text="Append-only: Each entry is 'MM-DD-YYYY, initials, description'; entries separated by semicolon. Use form to add, not edit.", null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='samplingProtocol',
            field=models.TextField(blank=True, help_text="Append-only: Each entry is 'MM-DD-YYYY, initials, description'; entries separated by semicolon. Use form to add, not edit.", null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='sex',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('.', '.')], help_text='Dropdown: male/female/.', max_length=6),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='specificEpithet',
            field=models.CharField(blank=True, help_text='Text/write in.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='specimenNumber',
            field=models.CharField(blank=True, default=None, help_text='Manual entry. If duplicate, error.', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='subfamily',
            field=models.CharField(blank=True, help_text='Text/write in.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='subtribe',
            field=models.CharField(blank=True, help_text='Text/write in.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='tribe',
            field=models.CharField(blank=True, help_text='Text/write in.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='uploaded_iNaturalist',
            field=models.CharField(choices=[('TRUE', 'TRUE'), ('FALSE', 'FALSE')], help_text='Dropdown: TRUE/FALSE.', max_length=5),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='year',
            field=models.CharField(blank=True, help_text='Dropdown/typeable: 1900-2050.', max_length=4, null=True),
        ),
    ]
