# Generated by Django 5.2.4 on 2025-08-10 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butterflies', '0011_alter_initials_initials_alter_initials_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specimen',
            options={'ordering': ['modified', 'locality', 'decimalLatitude', 'decimalLongitude', 'exact_loc', 'coordinateUncertaintyInMeters', 'georeferencedBy', 'georeferencedDate', 'georeferenceProtocol', 'minimumElevationInMeters', 'maximumElevationInMeters', 'localityDescriptionNotes', 'specimenNumber', 'catalogNumber', 'recordedBy', 'sex', 'uploaded_iNaturalist', 'behavior', 'occurrenceRemarks', 'disposition', 'year', 'month', 'day', 'eventTime', 'eventDate', 'habitatNotes', 'samplingProtocol', 'family', 'subfamily', 'tribe', 'subtribe', 'genus', 'specificEpithet', 'infraspecificEpithet', 'identifiedBy', 'dateIdentified', 'identificationReferences', 'identificationRemarks']},
        ),
    ]
