# Generated by Django 5.2.4 on 2025-08-11 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butterflies', '0012_alter_specimen_options'),
        ('butterflies', '0012_reorder_specimen_fields'),
    ]

    operations = [
    ]
