# Generated by Django 5.2.4 on 2025-08-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butterflies', '0013_merge_20250811_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='dateIdentified',
            field=models.CharField(blank=True, help_text='Date in any format.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='eventDate',
            field=models.CharField(blank=True, help_text='Date in any format.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='eventTime',
            field=models.CharField(blank=True, help_text='Time in any format.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='specimen',
            name='georeferencedDate',
            field=models.CharField(blank=True, help_text='Date in any format.', max_length=100, null=True),
        ),
    ]
