# Generated by Django 5.2.4 on 2025-08-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butterflies', '0012_use_natural_keys'),
        ('butterflies', '0019_remove_uploaded_inaturalist'),
    ]

    operations = [
    ]
