# Generated by Django 5.2.4 on 2025-08-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butterflies', '0021_fix_foreign_key_types'),
        ('butterflies', '0021_fix_foreign_keys'),
    ]

    operations = [
    ]
